/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Bandwidth.Standard.Client;
using Bandwidth.Standard.Api;
// uncomment below to import models
//using Bandwidth.Standard.Model;

namespace Bandwidth.Standard.Test.Api
{
    /// <summary>
    ///  Class for testing PhoneNumberLookupApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PhoneNumberLookupApiTests : IDisposable
    {
        private PhoneNumberLookupApi instance;

        public PhoneNumberLookupApiTests()
        {
            instance = new PhoneNumberLookupApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhoneNumberLookupApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PhoneNumberLookupApi
            //Assert.IsType<PhoneNumberLookupApi>(instance);
        }

        /// <summary>
        /// Test CreateLookup
        /// </summary>
        [Fact]
        public void CreateLookupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //LookupRequest lookupRequest = null;
            //var response = instance.CreateLookup(accountId, lookupRequest);
            //Assert.IsType<CreateLookupResponse>(response);
        }

        /// <summary>
        /// Test GetLookupStatus
        /// </summary>
        [Fact]
        public void GetLookupStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string requestId = null;
            //var response = instance.GetLookupStatus(accountId, requestId);
            //Assert.IsType<LookupStatus>(response);
        }
    }
}
