/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bandwidth.Standard.Model;
using Bandwidth.Standard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bandwidth.Standard.Test.Unit.Model
{
    /// <summary>
    ///  Class for testing BrtcErrorSource
    /// </summary>
    public class BrtcErrorSourceTests : IDisposable
    {
        private BrtcErrorSource instance;

        public BrtcErrorSourceTests()
        {
            instance = new BrtcErrorSource(
                varParameter: "accountId",
                field: "type",
                header: "Authorization",
                reference: "https://developer.bandwidth.com/errors/1001"
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BrtcErrorSource
        /// </summary>
        [Fact]
        public void BrtcErrorSourceInstanceTest()
        {
            Assert.IsType<BrtcErrorSource>(instance);
        }

        /// <summary>
        /// Test the property 'Parameter'
        /// </summary>
        [Fact]
        public void ParameterTest()
        {
            Assert.IsType<string>(instance.Parameter);
            Assert.Equal("accountId", instance.Parameter);
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            Assert.IsType<string>(instance.Field);
            Assert.Equal("type", instance.Field);
        }

        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Fact]
        public void HeaderTest()
        {
            Assert.IsType<string>(instance.Header);
            Assert.Equal("Authorization", instance.Header);
        }

        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            Assert.IsType<string>(instance.Reference);
            Assert.Equal("https://developer.bandwidth.com/errors/1001", instance.Reference);
        }
    }
}
