/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bandwidth.Standard.Model;
using Bandwidth.Standard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bandwidth.Standard.Test.Unit.Model
{
    /// <summary>
    ///  Class for testing LookupErrorSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LookupErrorSchemaTests : IDisposable
    {
        private LookupErrorSchema instance;
        private LookupErrorSchemaMeta meta;

        public LookupErrorSchemaTests()
        {
            meta = new LookupErrorSchemaMeta(
                phoneNumbers: new List<string> { "+1234567890", "+1987654321" },
                message: "An error occurred during the lookup process.",
                code: 12345
            );
            instance = new LookupErrorSchema(
                code: "1234",
                description: "Bad Request",
                type: "ValidationError",
                meta: meta
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LookupErrorSchema
        /// </summary>
        [Fact]
        public void LookupErrorSchemaInstanceTest()
        {
            Assert.IsType<LookupErrorSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            Assert.IsType<string>(instance.Code);
            Assert.Equal("1234", instance.Code);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            Assert.IsType<string>(instance.Description);
            Assert.Equal("Bad Request", instance.Description);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            Assert.IsType<string>(instance.Type);
            Assert.Equal("ValidationError", instance.Type);
        }

        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            Assert.IsType<LookupErrorSchemaMeta>(instance.Meta);
            Assert.Equal(meta, instance.Meta);
        }
    }
}
