/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bandwidth.Standard.Model;
using Bandwidth.Standard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bandwidth.Standard.Test.Unit.Model
{
    /// <summary>
    ///  Class for testing MultiChannelChannelListSMSObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MultiChannelChannelListSMSObjectTests : IDisposable
    {
        private MultiChannelChannelListSMSObject instance;

        public MultiChannelChannelListSMSObjectTests()
        {
            instance = new MultiChannelChannelListSMSObject(
                from: "1234567890",
                applicationId: "app-1234",
                channel: MultiChannelMessageChannelEnum.SMS,
                content: new SmsMessageContent(
                    text: "Test SMS message"
                )
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MultiChannelChannelListSMSObject
        /// </summary>
        [Fact]
        public void MultiChannelChannelListSMSObjectInstanceTest()
        {
            Assert.IsType<MultiChannelChannelListSMSObject>(instance);
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            Assert.IsType<string>(instance.From);
            Assert.Equal("1234567890", instance.From);
        }

        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            Assert.IsType<string>(instance.ApplicationId);
            Assert.Equal("app-1234", instance.ApplicationId);
        }

        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Fact]
        public void ChannelTest()
        {
            Assert.IsType<MultiChannelMessageChannelEnum>(instance.Channel);
            Assert.Equal(MultiChannelMessageChannelEnum.SMS, instance.Channel);
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            Assert.IsType<SmsMessageContent>(instance.Content);
        }
    }
}
