/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bandwidth.Standard.Model;
using Bandwidth.Standard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bandwidth.Standard.Test.Unit.Model
{
    /// <summary>
    ///  Class for testing MultiChannelChannelListRequestObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MultiChannelChannelListRequestObjectTests : IDisposable
    {
        private MultiChannelChannelListRequestObject instanceSms;
        private MultiChannelChannelListRequestObject instanceMms;
        private MultiChannelChannelListRequestObject instanceRbm;

        public MultiChannelChannelListRequestObjectTests()
        {
            instanceSms = new MultiChannelChannelListRequestObject(
                new MultiChannelChannelListSMSObject(
                    from: "1234567890",
                    applicationId: "app-1234",
                    channel: MultiChannelMessageChannelEnum.SMS,
                    content: new SmsMessageContent(
                        text: "Test SMS message"
                    )
                )
            );
            instanceMms = new MultiChannelChannelListRequestObject(
                new MultiChannelChannelListMMSObject(
                    from: "TestFrom",
                    applicationId: "TestApplicationId",
                    channel: MultiChannelMessageChannelEnum.MMS,
                    content: new MmsMessageContent()
                )
            );
            instanceRbm = new MultiChannelChannelListRequestObject(
                new MultiChannelChannelListRBMObject(
                    from: "1234567890",
                    applicationId: "app-1234",
                    channel: MultiChannelMessageChannelEnum.RBM,
                    content: new MultiChannelChannelListRBMObjectAllOfContent(
                        new RbmMessageContentText(
                            text: "Test RBM message",
                            suggestions: new List<MultiChannelAction>()
                        )
                    )
                )
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MultiChannelChannelListRequestObject
        /// </summary>
        [Fact]
        public void MultiChannelChannelListRequestObjectInstanceTest()
        {
            Assert.IsType<MultiChannelChannelListRequestObject>(instanceSms);
            Assert.IsType<MultiChannelChannelListSMSObject>(instanceSms.ActualInstance);
            Assert.IsType<MultiChannelChannelListRequestObject>(instanceMms);
            Assert.IsType<MultiChannelChannelListMMSObject>(instanceMms.ActualInstance);
            Assert.IsType<MultiChannelChannelListRequestObject>(instanceRbm);
            Assert.IsType<MultiChannelChannelListRBMObject>(instanceRbm.ActualInstance);
        }
    }
}
