/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bandwidth.Standard.Model;
using Bandwidth.Standard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bandwidth.Standard.Test.Unit.Model
{
    /// <summary>
    ///  Class for testing RbmMessageMedia
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RbmMessageMediaTests : IDisposable
    {
        private RbmMessageMedia instance;

        public RbmMessageMediaTests()
        {
            instance = new RbmMessageMedia(
                media: new RbmMessageContentFile(
                    fileUrl: "https://test.url/",
                    thumbnailUrl: "https://test.url/"
                ),
                suggestions: new List<MultiChannelAction>
                {
                    new MultiChannelAction(new RbmActionBase(
                        type: RbmActionTypeEnum.REPLY,
                        text: "Test",
                        postbackData: new byte[] { 1, 2, 3 }
                    ))
                }
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RbmMessageMedia
        /// </summary>
        [Fact]
        public void RbmMessageMediaInstanceTest()
        {
            Assert.IsType<RbmMessageMedia>(instance);
        }

        /// <summary>
        /// Test the property 'Media'
        /// </summary>
        [Fact]
        public void MediaTest()
        {
            Assert.IsType<RbmMessageContentFile>(instance.Media);
        }

        /// <summary>
        /// Test the property 'Suggestions'
        /// </summary>
        [Fact]
        public void SuggestionsTest()
        {
            Assert.IsType<List<MultiChannelAction>>(instance.Suggestions);
        }
    }
}
