/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bandwidth.Standard.Model;
using Bandwidth.Standard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bandwidth.Standard.Test.Model
{
    /// <summary>
    ///  Class for testing RbmSuggestionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RbmSuggestionResponseTests : IDisposable
    {
        private RbmSuggestionResponse instance;

        public RbmSuggestionResponseTests()
        {
            instance = new RbmSuggestionResponse(
                text: "Sample suggestion text",
                postbackData: new byte[] { 1, 2, 3 }
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RbmSuggestionResponse
        /// </summary>
        [Fact]
        public void RbmSuggestionResponseInstanceTest()
        {
            Assert.IsType<RbmSuggestionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            Assert.IsType<string>(instance.Text);
            Assert.Equal("Sample suggestion text", instance.Text);
        }

        /// <summary>
        /// Test the property 'PostbackData'
        /// </summary>
        [Fact]
        public void PostbackDataTest()
        {
            Assert.IsType<byte[]>(instance.PostbackData);
            Assert.Equal(new byte[] { 1, 2, 3 }, instance.PostbackData);
        }
    }
}
