/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Bandwidth.Standard.Client.OpenAPIDateConverter;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// The detected language for this transcription.
    /// </summary>
    /// <value>The detected language for this transcription.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CallTranscriptionDetectedLanguageEnum
    {
        /// <summary>
        /// Enum EnUS for value: en-US
        /// </summary>
        [EnumMember(Value = "en-US")]
        EnUS = 1,

        /// <summary>
        /// Enum EsUS for value: es-US
        /// </summary>
        [EnumMember(Value = "es-US")]
        EsUS = 2,

        /// <summary>
        /// Enum FrFR for value: fr-FR
        /// </summary>
        [EnumMember(Value = "fr-FR")]
        FrFR = 3
    }

}
