/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Bandwidth.Standard.Client.OpenAPIDateConverter;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// Defines completedLookupStatusEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CompletedLookupStatusEnum
    {
        /// <summary>
        /// Enum COMPLETE for value: COMPLETE
        /// </summary>
        [EnumMember(Value = "COMPLETE")]
        COMPLETE = 1,

        /// <summary>
        /// Enum PARTIALCOMPLETE for value: PARTIAL_COMPLETE
        /// </summary>
        [EnumMember(Value = "PARTIAL_COMPLETE")]
        PARTIALCOMPLETE = 2,

        /// <summary>
        /// Enum FAILED for value: FAILED
        /// </summary>
        [EnumMember(Value = "FAILED")]
        FAILED = 3
    }

}
