/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Bandwidth.Standard.Client.OpenAPIDateConverter;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// Defines lineTypeEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LineTypeEnum
    {
        /// <summary>
        /// Enum FIXED for value: FIXED
        /// </summary>
        [EnumMember(Value = "FIXED")]
        FIXED = 1,

        /// <summary>
        /// Enum VOIPFIXED for value: VOIP-FIXED
        /// </summary>
        [EnumMember(Value = "VOIP-FIXED")]
        VOIPFIXED = 2,

        /// <summary>
        /// Enum MOBILE for value: MOBILE
        /// </summary>
        [EnumMember(Value = "MOBILE")]
        MOBILE = 3,

        /// <summary>
        /// Enum VOIP for value: VOIP
        /// </summary>
        [EnumMember(Value = "VOIP")]
        VOIP = 4
    }

}
