/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Bandwidth.Standard.Client.OpenAPIDateConverter;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// LookupErrorSchema
    /// </summary>
    [DataContract(Name = "lookupErrorSchema")]
    public partial class LookupErrorSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LookupErrorSchema" /> class.
        /// </summary>
        /// <param name="code">Validation error code.</param>
        /// <param name="description">Description of validation error.</param>
        /// <param name="type">Type of validation error.</param>
        /// <param name="meta">meta.</param>
        public LookupErrorSchema(string code = default(string), string description = default(string), string type = default(string), LookupErrorSchemaMeta meta = default(LookupErrorSchemaMeta))
        {
            this.Code = code;
            this.Description = description;
            this.Type = type;
            this.Meta = meta;
        }

        /// <summary>
        /// Validation error code
        /// </summary>
        /// <value>Validation error code</value>
        /// <example>NO-MATCH</example>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public string Code { get; set; }

        /// <summary>
        /// Description of validation error
        /// </summary>
        /// <value>Description of validation error</value>
        /// <example>Example error description</example>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Type of validation error
        /// </summary>
        /// <value>Type of validation error</value>
        /// <example>NumberInventory</example>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Meta
        /// </summary>
        [DataMember(Name = "meta", EmitDefaultValue = false)]
        public LookupErrorSchemaMeta Meta { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LookupErrorSchema {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Meta: ").Append(Meta).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
