/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Bandwidth.Standard.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// MultiChannelAction
    /// </summary>
    [JsonConverter(typeof(MultiChannelActionJsonConverter))]
    [DataContract(Name = "multiChannelAction")]
    public partial class MultiChannelAction : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultiChannelAction" /> class
        /// with the <see cref="RbmActionBase" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of RbmActionBase.</param>
        public MultiChannelAction(RbmActionBase actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiChannelAction" /> class
        /// with the <see cref="RbmActionDial" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of RbmActionDial.</param>
        public MultiChannelAction(RbmActionDial actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiChannelAction" /> class
        /// with the <see cref="RbmActionViewLocation" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of RbmActionViewLocation.</param>
        public MultiChannelAction(RbmActionViewLocation actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiChannelAction" /> class
        /// with the <see cref="MultiChannelActionCalendarEvent" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MultiChannelActionCalendarEvent.</param>
        public MultiChannelAction(MultiChannelActionCalendarEvent actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiChannelAction" /> class
        /// with the <see cref="RbmActionOpenUrl" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of RbmActionOpenUrl.</param>
        public MultiChannelAction(RbmActionOpenUrl actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(MultiChannelActionCalendarEvent) || value is MultiChannelActionCalendarEvent)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(RbmActionBase) || value is RbmActionBase)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(RbmActionDial) || value is RbmActionDial)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(RbmActionOpenUrl) || value is RbmActionOpenUrl)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(RbmActionViewLocation) || value is RbmActionViewLocation)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: MultiChannelActionCalendarEvent, RbmActionBase, RbmActionDial, RbmActionOpenUrl, RbmActionViewLocation");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `RbmActionBase`. If the actual instance is not `RbmActionBase`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of RbmActionBase</returns>
        public RbmActionBase GetRbmActionBase()
        {
            return (RbmActionBase)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `RbmActionDial`. If the actual instance is not `RbmActionDial`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of RbmActionDial</returns>
        public RbmActionDial GetRbmActionDial()
        {
            return (RbmActionDial)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `RbmActionViewLocation`. If the actual instance is not `RbmActionViewLocation`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of RbmActionViewLocation</returns>
        public RbmActionViewLocation GetRbmActionViewLocation()
        {
            return (RbmActionViewLocation)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MultiChannelActionCalendarEvent`. If the actual instance is not `MultiChannelActionCalendarEvent`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MultiChannelActionCalendarEvent</returns>
        public MultiChannelActionCalendarEvent GetMultiChannelActionCalendarEvent()
        {
            return (MultiChannelActionCalendarEvent)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `RbmActionOpenUrl`. If the actual instance is not `RbmActionOpenUrl`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of RbmActionOpenUrl</returns>
        public RbmActionOpenUrl GetRbmActionOpenUrl()
        {
            return (RbmActionOpenUrl)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MultiChannelAction {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, MultiChannelAction.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of MultiChannelAction
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of MultiChannelAction</returns>
        public static MultiChannelAction FromJson(string jsonString)
        {
            MultiChannelAction newMultiChannelAction = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newMultiChannelAction;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MultiChannelActionCalendarEvent).GetProperty("AdditionalProperties") == null)
                {
                    newMultiChannelAction = new MultiChannelAction(JsonConvert.DeserializeObject<MultiChannelActionCalendarEvent>(jsonString, MultiChannelAction.SerializerSettings));
                }
                else
                {
                    newMultiChannelAction = new MultiChannelAction(JsonConvert.DeserializeObject<MultiChannelActionCalendarEvent>(jsonString, MultiChannelAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("MultiChannelActionCalendarEvent");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MultiChannelActionCalendarEvent: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(RbmActionBase).GetProperty("AdditionalProperties") == null)
                {
                    newMultiChannelAction = new MultiChannelAction(JsonConvert.DeserializeObject<RbmActionBase>(jsonString, MultiChannelAction.SerializerSettings));
                }
                else
                {
                    newMultiChannelAction = new MultiChannelAction(JsonConvert.DeserializeObject<RbmActionBase>(jsonString, MultiChannelAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("RbmActionBase");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into RbmActionBase: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(RbmActionDial).GetProperty("AdditionalProperties") == null)
                {
                    newMultiChannelAction = new MultiChannelAction(JsonConvert.DeserializeObject<RbmActionDial>(jsonString, MultiChannelAction.SerializerSettings));
                }
                else
                {
                    newMultiChannelAction = new MultiChannelAction(JsonConvert.DeserializeObject<RbmActionDial>(jsonString, MultiChannelAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("RbmActionDial");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into RbmActionDial: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(RbmActionOpenUrl).GetProperty("AdditionalProperties") == null)
                {
                    newMultiChannelAction = new MultiChannelAction(JsonConvert.DeserializeObject<RbmActionOpenUrl>(jsonString, MultiChannelAction.SerializerSettings));
                }
                else
                {
                    newMultiChannelAction = new MultiChannelAction(JsonConvert.DeserializeObject<RbmActionOpenUrl>(jsonString, MultiChannelAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("RbmActionOpenUrl");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into RbmActionOpenUrl: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(RbmActionViewLocation).GetProperty("AdditionalProperties") == null)
                {
                    newMultiChannelAction = new MultiChannelAction(JsonConvert.DeserializeObject<RbmActionViewLocation>(jsonString, MultiChannelAction.SerializerSettings));
                }
                else
                {
                    newMultiChannelAction = new MultiChannelAction(JsonConvert.DeserializeObject<RbmActionViewLocation>(jsonString, MultiChannelAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("RbmActionViewLocation");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into RbmActionViewLocation: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newMultiChannelAction;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for MultiChannelAction
    /// </summary>
    public class MultiChannelActionJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(MultiChannelAction).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return MultiChannelAction.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return MultiChannelAction.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
