/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Bandwidth.Standard.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// MultiChannelChannelListResponseObject
    /// </summary>
    [JsonConverter(typeof(MultiChannelChannelListResponseObjectJsonConverter))]
    [DataContract(Name = "multiChannelChannelListResponseObject")]
    public partial class MultiChannelChannelListResponseObject : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultiChannelChannelListResponseObject" /> class
        /// with the <see cref="MultiChannelChannelListRBMResponseObject" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MultiChannelChannelListRBMResponseObject.</param>
        public MultiChannelChannelListResponseObject(MultiChannelChannelListRBMResponseObject actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiChannelChannelListResponseObject" /> class
        /// with the <see cref="MultiChannelChannelListSMSResponseObject" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MultiChannelChannelListSMSResponseObject.</param>
        public MultiChannelChannelListResponseObject(MultiChannelChannelListSMSResponseObject actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiChannelChannelListResponseObject" /> class
        /// with the <see cref="MultiChannelChannelListMMSResponseObject" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MultiChannelChannelListMMSResponseObject.</param>
        public MultiChannelChannelListResponseObject(MultiChannelChannelListMMSResponseObject actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(MultiChannelChannelListMMSResponseObject))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(MultiChannelChannelListRBMResponseObject))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(MultiChannelChannelListSMSResponseObject))
                {
                    _actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: MultiChannelChannelListMMSResponseObject, MultiChannelChannelListRBMResponseObject, MultiChannelChannelListSMSResponseObject");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `MultiChannelChannelListRBMResponseObject`. If the actual instance is not `MultiChannelChannelListRBMResponseObject`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MultiChannelChannelListRBMResponseObject</returns>
        public MultiChannelChannelListRBMResponseObject GetMultiChannelChannelListRBMResponseObject()
        {
            return (MultiChannelChannelListRBMResponseObject)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MultiChannelChannelListSMSResponseObject`. If the actual instance is not `MultiChannelChannelListSMSResponseObject`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MultiChannelChannelListSMSResponseObject</returns>
        public MultiChannelChannelListSMSResponseObject GetMultiChannelChannelListSMSResponseObject()
        {
            return (MultiChannelChannelListSMSResponseObject)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MultiChannelChannelListMMSResponseObject`. If the actual instance is not `MultiChannelChannelListMMSResponseObject`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MultiChannelChannelListMMSResponseObject</returns>
        public MultiChannelChannelListMMSResponseObject GetMultiChannelChannelListMMSResponseObject()
        {
            return (MultiChannelChannelListMMSResponseObject)ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MultiChannelChannelListResponseObject {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, MultiChannelChannelListResponseObject.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of MultiChannelChannelListResponseObject
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of MultiChannelChannelListResponseObject</returns>
        public static MultiChannelChannelListResponseObject FromJson(string jsonString)
        {
            MultiChannelChannelListResponseObject newMultiChannelChannelListResponseObject = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newMultiChannelChannelListResponseObject;
            }

            try
            {
                newMultiChannelChannelListResponseObject = new MultiChannelChannelListResponseObject(JsonConvert.DeserializeObject<MultiChannelChannelListMMSResponseObject>(jsonString, MultiChannelChannelListResponseObject.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newMultiChannelChannelListResponseObject;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MultiChannelChannelListMMSResponseObject: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newMultiChannelChannelListResponseObject = new MultiChannelChannelListResponseObject(JsonConvert.DeserializeObject<MultiChannelChannelListRBMResponseObject>(jsonString, MultiChannelChannelListResponseObject.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newMultiChannelChannelListResponseObject;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MultiChannelChannelListRBMResponseObject: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newMultiChannelChannelListResponseObject = new MultiChannelChannelListResponseObject(JsonConvert.DeserializeObject<MultiChannelChannelListSMSResponseObject>(jsonString, MultiChannelChannelListResponseObject.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newMultiChannelChannelListResponseObject;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MultiChannelChannelListSMSResponseObject: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for MultiChannelChannelListResponseObject
    /// </summary>
    public class MultiChannelChannelListResponseObjectJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(MultiChannelChannelListResponseObject).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return MultiChannelChannelListResponseObject.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return MultiChannelChannelListResponseObject.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
