/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Bandwidth.Standard.Client.OpenAPIDateConverter;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// The channel of the multi-channel message.
    /// </summary>
    /// <value>The channel of the multi-channel message.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MultiChannelMessageChannelEnum
    {
        /// <summary>
        /// Enum RBM for value: RBM
        /// </summary>
        [EnumMember(Value = "RBM")]
        RBM = 1,

        /// <summary>
        /// Enum SMS for value: SMS
        /// </summary>
        [EnumMember(Value = "SMS")]
        SMS = 2,

        /// <summary>
        /// Enum MMS for value: MMS
        /// </summary>
        [EnumMember(Value = "MMS")]
        MMS = 3
    }

}
