/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Bandwidth.Standard.Client.OpenAPIDateConverter;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// RbmMessageContentFile
    /// </summary>
    [DataContract(Name = "rbmMessageContentFile")]
    public partial class RbmMessageContentFile : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RbmMessageContentFile" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RbmMessageContentFile() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RbmMessageContentFile" /> class.
        /// </summary>
        /// <param name="fileUrl">The URL of the media file. 100MB is the maximum file size. (required).</param>
        /// <param name="thumbnailUrl">The URL of the thumbnail image. Applies only to video file media..</param>
        public RbmMessageContentFile(string fileUrl = default(string), string thumbnailUrl = default(string))
        {
            // to ensure "fileUrl" is required (not null)
            if (fileUrl == null)
            {
                throw new ArgumentNullException("fileUrl is a required property for RbmMessageContentFile and cannot be null");
            }
            this.FileUrl = fileUrl;
            this.ThumbnailUrl = thumbnailUrl;
        }

        /// <summary>
        /// The URL of the media file. 100MB is the maximum file size.
        /// </summary>
        /// <value>The URL of the media file. 100MB is the maximum file size.</value>
        /// <example>https://dev.bandwidth.com/images/bandwidth-logo.png</example>
        [DataMember(Name = "fileUrl", IsRequired = true, EmitDefaultValue = true)]
        public string FileUrl { get; set; }

        /// <summary>
        /// The URL of the thumbnail image. Applies only to video file media.
        /// </summary>
        /// <value>The URL of the thumbnail image. Applies only to video file media.</value>
        /// <example>https://dev.bandwidth.com/images/bandwidth-logo.png</example>
        [DataMember(Name = "thumbnailUrl", EmitDefaultValue = false)]
        public string ThumbnailUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RbmMessageContentFile {\n");
            sb.Append("  FileUrl: ").Append(FileUrl).Append("\n");
            sb.Append("  ThumbnailUrl: ").Append(ThumbnailUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // FileUrl (string) maxLength
            if (this.FileUrl != null && this.FileUrl.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for FileUrl, length must be less than 1000.", new [] { "FileUrl" });
            }

            // ThumbnailUrl (string) maxLength
            if (this.ThumbnailUrl != null && this.ThumbnailUrl.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for ThumbnailUrl, length must be less than 1000.", new [] { "ThumbnailUrl" });
            }

            yield break;
        }
    }

}
