/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Bandwidth.Standard.Client.OpenAPIDateConverter;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// RecordingTranscriptionClip
    /// </summary>
    [DataContract(Name = "recordingTranscriptionClip")]
    public partial class RecordingTranscriptionClip : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordingTranscriptionClip" /> class.
        /// </summary>
        /// <param name="speaker">Zero-based index identifying the speaker..</param>
        /// <param name="text">The transcribed text of this clip..</param>
        /// <param name="confidence">How confident the transcription engine was in transcribing this clip (from &#x60;0.0&#x60; to &#x60;1.0&#x60;)..</param>
        /// <param name="startTimeSeconds">The start time of this clip within the recording, in seconds..</param>
        /// <param name="endTimeSeconds">The end time of this clip within the recording, in seconds..</param>
        public RecordingTranscriptionClip(int speaker = default(int), string text = default(string), double confidence = default(double), double startTimeSeconds = default(double), double endTimeSeconds = default(double))
        {
            this.Speaker = speaker;
            this.Text = text;
            this.Confidence = confidence;
            this.StartTimeSeconds = startTimeSeconds;
            this.EndTimeSeconds = endTimeSeconds;
        }

        /// <summary>
        /// Zero-based index identifying the speaker.
        /// </summary>
        /// <value>Zero-based index identifying the speaker.</value>
        /// <example>0</example>
        [DataMember(Name = "speaker", EmitDefaultValue = false)]
        public int Speaker { get; set; }

        /// <summary>
        /// The transcribed text of this clip.
        /// </summary>
        /// <value>The transcribed text of this clip.</value>
        /// <example>Hi there, thanks for calling!</example>
        [DataMember(Name = "text", EmitDefaultValue = false)]
        public string Text { get; set; }

        /// <summary>
        /// How confident the transcription engine was in transcribing this clip (from &#x60;0.0&#x60; to &#x60;1.0&#x60;).
        /// </summary>
        /// <value>How confident the transcription engine was in transcribing this clip (from &#x60;0.0&#x60; to &#x60;1.0&#x60;).</value>
        /// <example>0.85</example>
        [DataMember(Name = "confidence", EmitDefaultValue = false)]
        public double Confidence { get; set; }

        /// <summary>
        /// The start time of this clip within the recording, in seconds.
        /// </summary>
        /// <value>The start time of this clip within the recording, in seconds.</value>
        /// <example>2.3</example>
        [DataMember(Name = "startTimeSeconds", EmitDefaultValue = false)]
        public double StartTimeSeconds { get; set; }

        /// <summary>
        /// The end time of this clip within the recording, in seconds.
        /// </summary>
        /// <value>The end time of this clip within the recording, in seconds.</value>
        /// <example>3.1</example>
        [DataMember(Name = "endTimeSeconds", EmitDefaultValue = false)]
        public double EndTimeSeconds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RecordingTranscriptionClip {\n");
            sb.Append("  Speaker: ").Append(Speaker).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Confidence: ").Append(Confidence).Append("\n");
            sb.Append("  StartTimeSeconds: ").Append(StartTimeSeconds).Append("\n");
            sb.Append("  EndTimeSeconds: ").Append(EndTimeSeconds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Confidence (double) maximum
            if (this.Confidence > (double)1)
            {
                yield return new ValidationResult("Invalid value for Confidence, must be a value less than or equal to 1.", new [] { "Confidence" });
            }

            // Confidence (double) minimum
            if (this.Confidence < (double)0)
            {
                yield return new ValidationResult("Invalid value for Confidence, must be a value greater than or equal to 0.", new [] { "Confidence" });
            }

            yield break;
        }
    }

}
