using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// This event is sent to the referCompleteUrl of the A-leg's &lt;Refer&gt; verb when the REFER attempt completes.
    /// </summary>
    [DataContract(Name = "referCompleteCallback")]
    public partial class ReferCompleteCallback : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReferCompleteCallback" /> class.
        /// </summary>
        public ReferCompleteCallback(
            string eventType = default(string),
            DateTime eventTime = default(DateTime),
            string accountId = default(string),
            string applicationId = default(string),
            string from = default(string),
            string to = default(string),
            CallDirectionEnum? direction = default(CallDirectionEnum?),
            string callId = default(string),
            string callUrl = default(string),
            DateTime startTime = default(DateTime),
            DateTime answerTime = default(DateTime),
            ReferCallStatusEnum referCallStatus = default(ReferCallStatusEnum),
            string tag = default(string),
            int? referSipResponseCode = default(int?),
            int? notifySipResponseCode = default(int?))
        {
            EventType = eventType;
            EventTime = eventTime;
            AccountId = accountId;
            ApplicationId = applicationId;
            From = from;
            To = to;
            Direction = direction;
            CallId = callId;
            CallUrl = callUrl;
            StartTime = startTime;
            AnswerTime = answerTime;
            ReferCallStatus = referCallStatus;
            Tag = tag;
            ReferSipResponseCode = referSipResponseCode;
            NotifySipResponseCode = notifySipResponseCode;
        }

        /// <summary>
        /// The event type. Always referComplete.
        /// </summary>
        [DataMember(Name = "eventType", EmitDefaultValue = false)]
        public string EventType { get; set; }

        /// <summary>
        /// The approximate UTC date and time when the event was generated by the Bandwidth server.
        /// </summary>
        [DataMember(Name = "eventTime", EmitDefaultValue = false)]
        public DateTime EventTime { get; set; }

        /// <summary>
        /// The user account associated with the call.
        /// </summary>
        [DataMember(Name = "accountId", EmitDefaultValue = false)]
        public string AccountId { get; set; }

        /// <summary>
        /// The id of the application associated with the call.
        /// </summary>
        [DataMember(Name = "applicationId", EmitDefaultValue = false)]
        public string ApplicationId { get; set; }

        /// <summary>
        /// The provided identifier of the caller.
        /// </summary>
        [DataMember(Name = "from", EmitDefaultValue = false)]
        public string From { get; set; }

        /// <summary>
        /// The phone number that received the call.
        /// </summary>
        [DataMember(Name = "to", EmitDefaultValue = false)]
        public string To { get; set; }

        /// <summary>
        /// Call direction.
        /// </summary>
        [DataMember(Name = "direction", EmitDefaultValue = false)]
        public CallDirectionEnum? Direction { get; set; }

        /// <summary>
        /// The call id associated with the event.
        /// </summary>
        [DataMember(Name = "callId", EmitDefaultValue = false)]
        public string CallId { get; set; }

        /// <summary>
        /// The URL of the call associated with the event.
        /// </summary>
        [DataMember(Name = "callUrl", EmitDefaultValue = false)]
        public string CallUrl { get; set; }

        /// <summary>
        /// Time the call was started.
        /// </summary>
        [DataMember(Name = "startTime", EmitDefaultValue = false)]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// Time the call was answered.
        /// </summary>
        [DataMember(Name = "answerTime", EmitDefaultValue = false)]
        public DateTime AnswerTime { get; set; }

        /// <summary>
        /// Whether REFER succeeded or failed.
        /// </summary>
        [DataMember(Name = "referCallStatus", EmitDefaultValue = false)]
        public ReferCallStatusEnum ReferCallStatus { get; set; }

        /// <summary>
        /// Optional custom string included in callbacks.
        /// </summary>
        [DataMember(Name = "tag", EmitDefaultValue = true)]
        public string Tag { get; set; }

        /// <summary>
        /// Optional SIP response code from the REFER transaction.
        /// </summary>
        [DataMember(Name = "referSipResponseCode", EmitDefaultValue = true)]
        public int? ReferSipResponseCode { get; set; }

        /// <summary>
        /// Optional SIP response code from the NOTIFY transaction.
        /// </summary>
        [DataMember(Name = "notifySipResponseCode", EmitDefaultValue = true)]
        public int? NotifySipResponseCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object.
        /// </summary>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReferCompleteCallback {\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  EventTime: ").Append(EventTime).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  ApplicationId: ").Append(ApplicationId).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Direction: ").Append(Direction).Append("\n");
            sb.Append("  CallId: ").Append(CallId).Append("\n");
            sb.Append("  CallUrl: ").Append(CallUrl).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  AnswerTime: ").Append(AnswerTime).Append("\n");
            sb.Append("  ReferCallStatus: ").Append(ReferCallStatus).Append("\n");
            sb.Append("  Tag: ").Append(Tag).Append("\n");
            sb.Append("  ReferSipResponseCode: ").Append(ReferSipResponseCode).Append("\n");
            sb.Append("  NotifySipResponseCode: ").Append(NotifySipResponseCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance.
        /// </summary>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
