// <auto-generated>
/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bandwidth.Standard.Client;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// Defines standaloneCardOrientationEnum
    /// </summary>
    public enum StandaloneCardOrientationEnum
    {
        /// <summary>
        /// Enum HORIZONTAL for value: HORIZONTAL
        /// </summary>
        HORIZONTAL = 1,

        /// <summary>
        /// Enum VERTICAL for value: VERTICAL
        /// </summary>
        VERTICAL = 2
    }

    /// <summary>
    /// Converts <see cref="StandaloneCardOrientationEnum"/> to and from the JSON value
    /// </summary>
    public static class StandaloneCardOrientationEnumValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="StandaloneCardOrientationEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StandaloneCardOrientationEnum FromString(string value)
        {
            if (value.Equals("HORIZONTAL"))
                return StandaloneCardOrientationEnum.HORIZONTAL;

            if (value.Equals("VERTICAL"))
                return StandaloneCardOrientationEnum.VERTICAL;

            throw new NotImplementedException($"Could not convert value to type StandaloneCardOrientationEnum: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="StandaloneCardOrientationEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StandaloneCardOrientationEnum? FromStringOrDefault(string value)
        {
            if (value.Equals("HORIZONTAL"))
                return StandaloneCardOrientationEnum.HORIZONTAL;

            if (value.Equals("VERTICAL"))
                return StandaloneCardOrientationEnum.VERTICAL;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StandaloneCardOrientationEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(StandaloneCardOrientationEnum value)
        {
            if (value == StandaloneCardOrientationEnum.HORIZONTAL)
                return "HORIZONTAL";

            if (value == StandaloneCardOrientationEnum.VERTICAL)
                return "VERTICAL";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StandaloneCardOrientationEnum"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class StandaloneCardOrientationEnumJsonConverter : JsonConverter<StandaloneCardOrientationEnum>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override StandaloneCardOrientationEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            StandaloneCardOrientationEnum? result = rawValue == null
                ? null
                : StandaloneCardOrientationEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the StandaloneCardOrientationEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="standaloneCardOrientationEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, StandaloneCardOrientationEnum standaloneCardOrientationEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(StandaloneCardOrientationEnumValueConverter.ToJsonValue(standaloneCardOrientationEnum).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StandaloneCardOrientationEnum"/>
    /// </summary>
    public class StandaloneCardOrientationEnumNullableJsonConverter : JsonConverter<StandaloneCardOrientationEnum?>
    {
        /// <summary>
        /// Returns a StandaloneCardOrientationEnum from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override StandaloneCardOrientationEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            StandaloneCardOrientationEnum? result = rawValue == null
                ? null
                : StandaloneCardOrientationEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the StandaloneCardOrientationEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="standaloneCardOrientationEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, StandaloneCardOrientationEnum? standaloneCardOrientationEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(standaloneCardOrientationEnum.HasValue ? StandaloneCardOrientationEnumValueConverter.ToJsonValue(standaloneCardOrientationEnum.Value).ToString() : "null");
        }
    }
}
