// <auto-generated>
/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Bandwidth.Standard.Client;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// The possible status callbacks when sending an MT SMS or MMS or RBM message: - &#x60;message-sending&#x60; indicates that Bandwidth is sending the message to the upstream provider. - &#x60;message-delivered&#x60; indicates that the message was successfully sent. - &#x60;message-failed&#x60; indicates that the message could not be sent to the intended recipient. - &#x60;message-read&#x60; indicates that the RBM message was read by the recipient.
    /// </summary>
    /// <value>The possible status callbacks when sending an MT SMS or MMS or RBM message: - &#x60;message-sending&#x60; indicates that Bandwidth is sending the message to the upstream provider. - &#x60;message-delivered&#x60; indicates that the message was successfully sent. - &#x60;message-failed&#x60; indicates that the message could not be sent to the intended recipient. - &#x60;message-read&#x60; indicates that the RBM message was read by the recipient.</value>
    public enum StatusCallbackTypeEnum
    {
        /// <summary>
        /// Enum MessageSending for value: message-sending
        /// </summary>
        MessageSending = 1,

        /// <summary>
        /// Enum MessageDelivered for value: message-delivered
        /// </summary>
        MessageDelivered = 2,

        /// <summary>
        /// Enum MessageFailed for value: message-failed
        /// </summary>
        MessageFailed = 3,

        /// <summary>
        /// Enum MessageRead for value: message-read
        /// </summary>
        MessageRead = 4
    }

    /// <summary>
    /// Converts <see cref="StatusCallbackTypeEnum"/> to and from the JSON value
    /// </summary>
    public static class StatusCallbackTypeEnumValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="StatusCallbackTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusCallbackTypeEnum FromString(string value)
        {
            if (value.Equals("message-sending"))
                return StatusCallbackTypeEnum.MessageSending;

            if (value.Equals("message-delivered"))
                return StatusCallbackTypeEnum.MessageDelivered;

            if (value.Equals("message-failed"))
                return StatusCallbackTypeEnum.MessageFailed;

            if (value.Equals("message-read"))
                return StatusCallbackTypeEnum.MessageRead;

            throw new NotImplementedException($"Could not convert value to type StatusCallbackTypeEnum: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="StatusCallbackTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusCallbackTypeEnum? FromStringOrDefault(string value)
        {
            if (value.Equals("message-sending"))
                return StatusCallbackTypeEnum.MessageSending;

            if (value.Equals("message-delivered"))
                return StatusCallbackTypeEnum.MessageDelivered;

            if (value.Equals("message-failed"))
                return StatusCallbackTypeEnum.MessageFailed;

            if (value.Equals("message-read"))
                return StatusCallbackTypeEnum.MessageRead;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusCallbackTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(StatusCallbackTypeEnum value)
        {
            if (value == StatusCallbackTypeEnum.MessageSending)
                return "message-sending";

            if (value == StatusCallbackTypeEnum.MessageDelivered)
                return "message-delivered";

            if (value == StatusCallbackTypeEnum.MessageFailed)
                return "message-failed";

            if (value == StatusCallbackTypeEnum.MessageRead)
                return "message-read";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StatusCallbackTypeEnum"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class StatusCallbackTypeEnumJsonConverter : JsonConverter<StatusCallbackTypeEnum>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override StatusCallbackTypeEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            StatusCallbackTypeEnum? result = rawValue == null
                ? null
                : StatusCallbackTypeEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the StatusCallbackTypeEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="statusCallbackTypeEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, StatusCallbackTypeEnum statusCallbackTypeEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(StatusCallbackTypeEnumValueConverter.ToJsonValue(statusCallbackTypeEnum).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StatusCallbackTypeEnum"/>
    /// </summary>
    public class StatusCallbackTypeEnumNullableJsonConverter : JsonConverter<StatusCallbackTypeEnum?>
    {
        /// <summary>
        /// Returns a StatusCallbackTypeEnum from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override StatusCallbackTypeEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            StatusCallbackTypeEnum? result = rawValue == null
                ? null
                : StatusCallbackTypeEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the StatusCallbackTypeEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="statusCallbackTypeEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, StatusCallbackTypeEnum? statusCallbackTypeEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(statusCallbackTypeEnum.HasValue ? StatusCallbackTypeEnumValueConverter.ToJsonValue(statusCallbackTypeEnum.Value).ToString() : "null");
        }
    }
}
