/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Bandwidth.Standard.Client.OpenAPIDateConverter;

namespace Bandwidth.Standard.Model
{
    /// <summary>
    /// TfvStatus
    /// </summary>
    [DataContract(Name = "tfvStatus")]
    public partial class TfvStatus : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public TfvStatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TfvStatus" /> class.
        /// </summary>
        /// <param name="phoneNumber">Toll-free telephone number in E.164 format..</param>
        /// <param name="status">status.</param>
        /// <param name="internalTicketNumber">Unique identifier (UUID) generated by Bandwidth to assist in tracking the verification status of a toll-free number - included in all webhook payloads..</param>
        /// <param name="declineReasonDescription">Explanation for why a verification request was declined..</param>
        /// <param name="resubmitAllowed">Whether a Toll-Free Verification request qualifies for resubmission via PUT..</param>
        /// <param name="createdDateTime">Date and time the verification request was created..</param>
        /// <param name="modifiedDateTime">Date and time the verification request was last modified..</param>
        /// <param name="submission">submission.</param>
        /// <param name="blocked">Whether a Toll-Free Verification is blocked. This attribute will only be defined when the number is blocked. (Not Available Until 5/28/2025).</param>
        /// <param name="blockedReason">The reason why the Toll-Free Verification is blocked. This attribute will only be defined when the number is blocked. (Not Available Until 5/28/2025).</param>
        public TfvStatus(string phoneNumber = default(string), TfvStatusEnum? status = default(TfvStatusEnum?), Guid internalTicketNumber = default(Guid), string declineReasonDescription = default(string), bool resubmitAllowed = default(bool), DateTime createdDateTime = default(DateTime), DateTime modifiedDateTime = default(DateTime), TfvSubmissionInfo submission = default(TfvSubmissionInfo), bool blocked = default(bool), string blockedReason = default(string))
        {
            this.PhoneNumber = phoneNumber;
            this.Status = status;
            this.InternalTicketNumber = internalTicketNumber;
            this.DeclineReasonDescription = declineReasonDescription;
            this.ResubmitAllowed = resubmitAllowed;
            this.CreatedDateTime = createdDateTime;
            this.ModifiedDateTime = modifiedDateTime;
            this.Submission = submission;
            this.Blocked = blocked;
            this.BlockedReason = blockedReason;
        }

        /// <summary>
        /// Toll-free telephone number in E.164 format.
        /// </summary>
        /// <value>Toll-free telephone number in E.164 format.</value>
        /// <example>+18005555555</example>
        [DataMember(Name = "phoneNumber", EmitDefaultValue = false)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Unique identifier (UUID) generated by Bandwidth to assist in tracking the verification status of a toll-free number - included in all webhook payloads.
        /// </summary>
        /// <value>Unique identifier (UUID) generated by Bandwidth to assist in tracking the verification status of a toll-free number - included in all webhook payloads.</value>
        /// <example>acde070d-8c4c-4f0d-9d8a-162843c10333</example>
        [DataMember(Name = "internalTicketNumber", EmitDefaultValue = false)]
        public Guid InternalTicketNumber { get; set; }

        /// <summary>
        /// Explanation for why a verification request was declined.
        /// </summary>
        /// <value>Explanation for why a verification request was declined.</value>
        /// <example>Invalid Information - Can&#39;t Validate URL - Website is not accessible / not available</example>
        [DataMember(Name = "declineReasonDescription", EmitDefaultValue = false)]
        public string DeclineReasonDescription { get; set; }

        /// <summary>
        /// Whether a Toll-Free Verification request qualifies for resubmission via PUT.
        /// </summary>
        /// <value>Whether a Toll-Free Verification request qualifies for resubmission via PUT.</value>
        /// <example>true</example>
        [DataMember(Name = "resubmitAllowed", EmitDefaultValue = true)]
        public bool ResubmitAllowed { get; set; }

        /// <summary>
        /// Date and time the verification request was created.
        /// </summary>
        /// <value>Date and time the verification request was created.</value>
        /// <example>2021-06-08T06:45:13Z</example>
        [DataMember(Name = "createdDateTime", EmitDefaultValue = false)]
        public DateTime CreatedDateTime { get; set; }

        /// <summary>
        /// Date and time the verification request was last modified.
        /// </summary>
        /// <value>Date and time the verification request was last modified.</value>
        /// <example>2021-06-08T06:45:13Z</example>
        [DataMember(Name = "modifiedDateTime", EmitDefaultValue = false)]
        public DateTime ModifiedDateTime { get; set; }

        /// <summary>
        /// Gets or Sets Submission
        /// </summary>
        [DataMember(Name = "submission", EmitDefaultValue = false)]
        public TfvSubmissionInfo Submission { get; set; }

        /// <summary>
        /// Whether a Toll-Free Verification is blocked. This attribute will only be defined when the number is blocked. (Not Available Until 5/28/2025)
        /// </summary>
        /// <value>Whether a Toll-Free Verification is blocked. This attribute will only be defined when the number is blocked. (Not Available Until 5/28/2025)</value>
        /// <example>true</example>
        [DataMember(Name = "blocked", EmitDefaultValue = true)]
        public bool Blocked { get; set; }

        /// <summary>
        /// The reason why the Toll-Free Verification is blocked. This attribute will only be defined when the number is blocked. (Not Available Until 5/28/2025)
        /// </summary>
        /// <value>The reason why the Toll-Free Verification is blocked. This attribute will only be defined when the number is blocked. (Not Available Until 5/28/2025)</value>
        /// <example>Toll-free number was used to send spam messages</example>
        [DataMember(Name = "blockedReason", EmitDefaultValue = false)]
        public string BlockedReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TfvStatus {\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  InternalTicketNumber: ").Append(InternalTicketNumber).Append("\n");
            sb.Append("  DeclineReasonDescription: ").Append(DeclineReasonDescription).Append("\n");
            sb.Append("  ResubmitAllowed: ").Append(ResubmitAllowed).Append("\n");
            sb.Append("  CreatedDateTime: ").Append(CreatedDateTime).Append("\n");
            sb.Append("  ModifiedDateTime: ").Append(ModifiedDateTime).Append("\n");
            sb.Append("  Submission: ").Append(Submission).Append("\n");
            sb.Append("  Blocked: ").Append(Blocked).Append("\n");
            sb.Append("  BlockedReason: ").Append(BlockedReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PhoneNumber (string) maxLength
            if (this.PhoneNumber != null && this.PhoneNumber.Length > 12)
            {
                yield return new ValidationResult("Invalid value for PhoneNumber, length must be less than 12.", new [] { "PhoneNumber" });
            }

            // PhoneNumber (string) minLength
            if (this.PhoneNumber != null && this.PhoneNumber.Length < 12)
            {
                yield return new ValidationResult("Invalid value for PhoneNumber, length must be greater than 12.", new [] { "PhoneNumber" });
            }

            if (this.PhoneNumber != null) {
                // PhoneNumber (string) pattern
                Regex regexPhoneNumber = new Regex(@"^\+1(800|833|844|855|866|877|888)[2-9]\d{6}$", RegexOptions.CultureInvariant);
                if (!regexPhoneNumber.Match(this.PhoneNumber).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PhoneNumber, must match a pattern of " + regexPhoneNumber, new [] { "PhoneNumber" });
                }
            }

            yield break;
        }
    }

}
