/*
 * Bandwidth.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Bandwidth.Standard;
using Bandwidth.Standard.Utilities;

namespace Bandwidth.Standard.TwoFactorAuth.Models
{
    public class TwoFactorVerifyCodeResponse 
    {
        public TwoFactorVerifyCodeResponse() { }

        public TwoFactorVerifyCodeResponse(bool? valid = null)
        {
            Valid = valid;
        }

        /// <summary>
        /// Getter for valid
        /// </summary>
        [JsonProperty("valid")]
        public bool? Valid { get; set; }

    }
}