/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bandwidth.Standard.Api;
using Bandwidth.Standard.Model;
using Bandwidth.Standard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bandwidth.Standard.Test.Model
{
    /// <summary>
    ///  Class for testing CreateCallResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCallResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateCallResponse
        //private CreateCallResponse instance;

        public CreateCallResponseTests()
        {
            // TODO uncomment below to create an instance of CreateCallResponse
            //instance = new CreateCallResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateCallResponse
        /// </summary>
        [Fact]
        public void CreateCallResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateCallResponse
            //Assert.IsType<CreateCallResponse>(instance);
        }


        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'CallId'
        /// </summary>
        [Fact]
        public void CallIdTest()
        {
            // TODO unit test for the property 'CallId'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'EnqueuedTime'
        /// </summary>
        [Fact]
        public void EnqueuedTimeTest()
        {
            // TODO unit test for the property 'EnqueuedTime'
        }
        /// <summary>
        /// Test the property 'CallUrl'
        /// </summary>
        [Fact]
        public void CallUrlTest()
        {
            // TODO unit test for the property 'CallUrl'
        }
        /// <summary>
        /// Test the property 'CallTimeout'
        /// </summary>
        [Fact]
        public void CallTimeoutTest()
        {
            // TODO unit test for the property 'CallTimeout'
        }
        /// <summary>
        /// Test the property 'CallbackTimeout'
        /// </summary>
        [Fact]
        public void CallbackTimeoutTest()
        {
            // TODO unit test for the property 'CallbackTimeout'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Fact]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'AnswerMethod'
        /// </summary>
        [Fact]
        public void AnswerMethodTest()
        {
            // TODO unit test for the property 'AnswerMethod'
        }
        /// <summary>
        /// Test the property 'AnswerUrl'
        /// </summary>
        [Fact]
        public void AnswerUrlTest()
        {
            // TODO unit test for the property 'AnswerUrl'
        }
        /// <summary>
        /// Test the property 'AnswerFallbackMethod'
        /// </summary>
        [Fact]
        public void AnswerFallbackMethodTest()
        {
            // TODO unit test for the property 'AnswerFallbackMethod'
        }
        /// <summary>
        /// Test the property 'AnswerFallbackUrl'
        /// </summary>
        [Fact]
        public void AnswerFallbackUrlTest()
        {
            // TODO unit test for the property 'AnswerFallbackUrl'
        }
        /// <summary>
        /// Test the property 'DisconnectMethod'
        /// </summary>
        [Fact]
        public void DisconnectMethodTest()
        {
            // TODO unit test for the property 'DisconnectMethod'
        }
        /// <summary>
        /// Test the property 'DisconnectUrl'
        /// </summary>
        [Fact]
        public void DisconnectUrlTest()
        {
            // TODO unit test for the property 'DisconnectUrl'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'FallbackUsername'
        /// </summary>
        [Fact]
        public void FallbackUsernameTest()
        {
            // TODO unit test for the property 'FallbackUsername'
        }
        /// <summary>
        /// Test the property 'FallbackPassword'
        /// </summary>
        [Fact]
        public void FallbackPasswordTest()
        {
            // TODO unit test for the property 'FallbackPassword'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }

    }

}
