/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bandwidth.Standard.Api;
using Bandwidth.Standard.Model;
using Bandwidth.Standard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bandwidth.Standard.Test.Model
{
    /// <summary>
    ///  Class for testing CreateParticipantResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateParticipantResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateParticipantResponse
        //private CreateParticipantResponse instance;

        public CreateParticipantResponseTests()
        {
            // TODO uncomment below to create an instance of CreateParticipantResponse
            //instance = new CreateParticipantResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateParticipantResponse
        /// </summary>
        [Fact]
        public void CreateParticipantResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateParticipantResponse
            //Assert.IsType<CreateParticipantResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Participant'
        /// </summary>
        [Fact]
        public void ParticipantTest()
        {
            // TODO unit test for the property 'Participant'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

    }

}
