/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bandwidth.Standard.Model;
using Bandwidth.Standard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bandwidth.Standard.Test.Model
{
    /// <summary>
    ///  Class for testing MachineDetectionConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MachineDetectionConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MachineDetectionConfiguration
        //private MachineDetectionConfiguration instance;

        public MachineDetectionConfigurationTests()
        {
            // TODO uncomment below to create an instance of MachineDetectionConfiguration
            //instance = new MachineDetectionConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MachineDetectionConfiguration
        /// </summary>
        [Fact]
        public void MachineDetectionConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" MachineDetectionConfiguration
            //Assert.IsType<MachineDetectionConfiguration>(instance);
        }

        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

        /// <summary>
        /// Test the property 'DetectionTimeout'
        /// </summary>
        [Fact]
        public void DetectionTimeoutTest()
        {
            // TODO unit test for the property 'DetectionTimeout'
        }

        /// <summary>
        /// Test the property 'SilenceTimeout'
        /// </summary>
        [Fact]
        public void SilenceTimeoutTest()
        {
            // TODO unit test for the property 'SilenceTimeout'
        }

        /// <summary>
        /// Test the property 'SpeechThreshold'
        /// </summary>
        [Fact]
        public void SpeechThresholdTest()
        {
            // TODO unit test for the property 'SpeechThreshold'
        }

        /// <summary>
        /// Test the property 'SpeechEndThreshold'
        /// </summary>
        [Fact]
        public void SpeechEndThresholdTest()
        {
            // TODO unit test for the property 'SpeechEndThreshold'
        }

        /// <summary>
        /// Test the property 'MachineSpeechEndThreshold'
        /// </summary>
        [Fact]
        public void MachineSpeechEndThresholdTest()
        {
            // TODO unit test for the property 'MachineSpeechEndThreshold'
        }

        /// <summary>
        /// Test the property 'DelayResult'
        /// </summary>
        [Fact]
        public void DelayResultTest()
        {
            // TODO unit test for the property 'DelayResult'
        }

        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Fact]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }

        /// <summary>
        /// Test the property 'CallbackMethod'
        /// </summary>
        [Fact]
        public void CallbackMethodTest()
        {
            // TODO unit test for the property 'CallbackMethod'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'FallbackUrl'
        /// </summary>
        [Fact]
        public void FallbackUrlTest()
        {
            // TODO unit test for the property 'FallbackUrl'
        }

        /// <summary>
        /// Test the property 'FallbackMethod'
        /// </summary>
        [Fact]
        public void FallbackMethodTest()
        {
            // TODO unit test for the property 'FallbackMethod'
        }

        /// <summary>
        /// Test the property 'FallbackUsername'
        /// </summary>
        [Fact]
        public void FallbackUsernameTest()
        {
            // TODO unit test for the property 'FallbackUsername'
        }

        /// <summary>
        /// Test the property 'FallbackPassword'
        /// </summary>
        [Fact]
        public void FallbackPasswordTest()
        {
            // TODO unit test for the property 'FallbackPassword'
        }
    }
}
