/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bandwidth.Standard.Model;
using Bandwidth.Standard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bandwidth.Standard.Test.Model
{
    /// <summary>
    ///  Class for testing MessagingCodeResponse
    /// </summary>
    public class MessagingCodeResponseTests : IDisposable
    {
        private MessagingCodeResponse instance;

        public MessagingCodeResponseTests()
        {
            instance = new MessagingCodeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessagingCodeResponse
        /// </summary>
        [Fact]
        public void MessagingCodeResponseInstanceTest()
        {
            Assert.IsType<MessagingCodeResponse>(instance);
        }


        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            instance.MessageId = "abc-123";
            Assert.IsType<string>(instance.MessageId);
            Assert.Equal("abc-123", instance.MessageId);
        }

    }

}
