/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bandwidth.Standard.Model;
using Bandwidth.Standard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bandwidth.Standard.Test.Model
{
    /// <summary>
    ///  Class for testing Transcription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TranscriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Transcription
        //private Transcription instance;

        public TranscriptionTests()
        {
            // TODO uncomment below to create an instance of Transcription
            //instance = new Transcription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Transcription
        /// </summary>
        [Fact]
        public void TranscriptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" Transcription
            //Assert.IsType<Transcription>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Confidence'
        /// </summary>
        [Fact]
        public void ConfidenceTest()
        {
            // TODO unit test for the property 'Confidence'
        }
    }
}
