/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Net;
using Xunit;

using Bandwidth.Standard.Client;
using Bandwidth.Standard.Api;
using Bandwidth.Standard.Model;

namespace Bandwidth.Standard.Test.Unit.Api
{
    /// <summary>
    ///  CallsApi Unit Tests
    /// </summary>
    public class CallsApiTests : IDisposable
    {
        private readonly CallsApi instance;

        private readonly string accountId = Environment.GetEnvironmentVariable("BW_ACCOUNT_ID");
        private readonly string userNumber = Environment.GetEnvironmentVariable("USER_NUMBER");
        private readonly string bwNumber = Environment.GetEnvironmentVariable("BW_NUMBER");
        private readonly string voiceApplicationId = Environment.GetEnvironmentVariable("BW_VOICE_APPLICATION_ID");
        private readonly string callbackUrl = Environment.GetEnvironmentVariable("BASE_CALLBACK_URL");

        private readonly string callId = "c-1234";
        private readonly string displayName = "C# SDK";
        private readonly CallbackMethodEnum answerMethod = CallbackMethodEnum.POST;
        private readonly CallbackMethodEnum disconnectMethod = CallbackMethodEnum.GET;
        private readonly double callTimeout = 30.0;
        private readonly double callbackTimeout = 15.0;

        public CallsApiTests()
        {
            Configuration configuration = new()
            {
                BasePath = "http://127.0.0.1:4010",
                IgnoreOperationServers = true,
                AccessToken = "abcd1234"
            };
            instance = new CallsApi(configuration);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CallsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            Assert.IsType<CallsApi>(instance);
        }

        /// <summary>
        /// Test CreateCall
        /// </summary>
        [Fact]
        public void CreateCallTest()
        {
            MachineDetectionConfiguration machineDetection = new(
                mode: MachineDetectionModeEnum.Async,
                detectionTimeout: 5.0,
                silenceTimeout: 5.0,
                speechThreshold: 5.0,
                speechEndThreshold: 5.0,
                delayResult: true,
                callbackUrl: callbackUrl,
                callbackMethod: CallbackMethodEnum.POST
            );

            CreateCall createCall = new(
                applicationId: voiceApplicationId,
                to: userNumber,
                from: bwNumber,
                privacy: false,
                displayName: displayName,
                answerUrl: callbackUrl,
                answerMethod: answerMethod,
                disconnectUrl: callbackUrl,
                disconnectMethod: disconnectMethod,
                machineDetection: machineDetection,
                callTimeout: callTimeout,
                callbackTimeout: callbackTimeout
            );

            ApiResponse<CreateCallResponse> response = instance.CreateCallWithHttpInfo(accountId, createCall);

            Assert.Equal(HttpStatusCode.Created, response.StatusCode);
            Assert.IsType<CreateCallResponse>(response.Data);
            Assert.Equal(36, response.Data.ApplicationId.Length);
            Assert.Equal(7, response.Data.AccountId.Length);
            Assert.Equal(47, response.Data.CallId.Length);
            Assert.Equal(12, response.Data.To.Length);
            Assert.Equal(12, response.Data.From.Length);
            Assert.IsType<DateTime>(response.Data.EnqueuedTime);
            Assert.IsType<string>(response.Data.CallUrl);
            Assert.IsType<double>(response.Data.CallTimeout);
            Assert.IsType<double>(response.Data.CallbackTimeout);
            Assert.IsType<string>(response.Data.Tag);
            Assert.IsType<CallbackMethodEnum>(response.Data.AnswerMethod);
            Assert.IsType<string>(response.Data.AnswerUrl);
            Assert.IsType<CallbackMethodEnum>(response.Data.AnswerFallbackMethod);
            Assert.IsType<string>(response.Data.AnswerFallbackUrl);
            Assert.IsType<CallbackMethodEnum>(response.Data.DisconnectMethod);
            Assert.IsType<string>(response.Data.DisconnectUrl);
            Assert.IsType<string>(response.Data.Username);
            Assert.IsType<string>(response.Data.Password);
            Assert.IsType<string>(response.Data.FallbackUsername);
            Assert.IsType<string>(response.Data.FallbackPassword);
            Assert.IsType<int>(response.Data.Priority);
        }

        /// <summary>
        /// Test GetCallState
        /// </summary>
        [Fact]
        public void GetCallStateTest()
        {
            ApiResponse<CallState> response = instance.GetCallStateWithHttpInfo(accountId, callId);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.IsType<CallState>(response.Data);
            Assert.Equal(36, response.Data.ApplicationId.Length);
            Assert.Equal(7, response.Data.AccountId.Length);
            Assert.Equal(47, response.Data.CallId.Length);
            Assert.Equal(47, response.Data.ParentCallId.Length);
            Assert.Equal(12, response.Data.To.Length);
            Assert.Equal(12, response.Data.From.Length);
            Assert.IsType<CallDirectionEnum>(response.Data.Direction);
            Assert.IsType<string>(response.Data.State);
            Assert.IsType<Dictionary<string, string>>(response.Data.StirShaken);
            Assert.IsType<string>(response.Data.Identity);
            Assert.IsType<DateTime>(response.Data.EnqueuedTime);
            Assert.IsType<DateTime>(response.Data.StartTime);
            Assert.IsType<DateTime>(response.Data.AnswerTime);
            Assert.IsType<DateTime>(response.Data.EndTime);
            Assert.IsType<string>(response.Data.DisconnectCause);
            Assert.IsType<DateTime>(response.Data.LastUpdate);
        }

        /// <summary>
        /// Test ListCalls
        /// </summary>
        [Fact]
        public void ListCallsTest()
        {
            ApiResponse<List<CallState>> response = instance.ListCallsWithHttpInfo(accountId, userNumber, bwNumber);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.IsType<CallState>(response.Data[0]);
            Assert.Equal(36, response.Data[0].ApplicationId.Length);
            Assert.Equal(7, response.Data[0].AccountId.Length);
            Assert.Equal(47, response.Data[0].CallId.Length);
            Assert.Equal(47, response.Data[0].ParentCallId.Length);
            Assert.Equal(12, response.Data[0].To.Length);
            Assert.Equal(12, response.Data[0].From.Length);
            Assert.IsType<CallDirectionEnum>(response.Data[0].Direction);
            Assert.IsType<string>(response.Data[0].State);
            Assert.IsType<Dictionary<string, string>>(response.Data[0].StirShaken);
            Assert.IsType<string>(response.Data[0].Identity);
            Assert.IsType<DateTime>(response.Data[0].EnqueuedTime);
            Assert.IsType<DateTime>(response.Data[0].StartTime);
            Assert.IsType<DateTime>(response.Data[0].AnswerTime);
            Assert.IsType<DateTime>(response.Data[0].EndTime);
            Assert.IsType<string>(response.Data[0].DisconnectCause);
            Assert.IsType<DateTime>(response.Data[0].LastUpdate);
        }

        /// <summary>
        /// Test UpdateCall
        /// </summary>
        [Fact]
        public void UpdateCallTest()
        {
            UpdateCall updateCall = new(
                state: CallStateEnum.Active
            );

            ApiResponse<object> response = instance.UpdateCallWithHttpInfo(accountId, callId, updateCall);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        }

        /// <summary>
        /// Test UpdateCallBxml
        /// </summary>
        [Fact]
        public void UpdateCallBxmlTest()
        {
            string updateCallBxml = "<Response><Hangup/></Response>";

            ApiResponse<object> response = instance.UpdateCallBxmlWithHttpInfo(accountId, callId, updateCallBxml);

            Assert.Equal(HttpStatusCode.NoContent, response.StatusCode);
        }
    }
}
