/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Net;
using Xunit;

using Bandwidth.Standard.Client;
using Bandwidth.Standard.Api;
using Bandwidth.Standard.Model;

namespace Bandwidth.Standard.Test.Unit.Api
{
    /// <summary>
    ///  ConferencesApi Unit Tests
    /// </summary>
    public class ConferencesApiTests : IDisposable
    {
        private readonly ConferencesApi instance;

        private readonly string accountId = Environment.GetEnvironmentVariable("BW_ACCOUNT_ID");
        private readonly string callbackUrl = Environment.GetEnvironmentVariable("BASE_CALLBACK_URL");

        private readonly string callId = "c-1234";
        private readonly string conferenceId = "c-4321";
        private readonly string recordingId = "r-1234";

        public ConferencesApiTests()
        {
            Configuration configuration = new()
            {
                BasePath = "http://127.0.0.1:4010",
                IgnoreOperationServers = true,
                AccessToken = "abcd1234"
            };
            instance = new ConferencesApi(configuration);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConferencesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            Assert.IsType<ConferencesApi>(instance);
        }

        /// <summary>
        /// Test DownloadConferenceRecording
        /// </summary>
        [Fact(Skip = "Can't set the correct Accept header for Prism")]
        public void DownloadConferenceRecordingTest()
        {
            ApiResponse<Stream> response = instance.DownloadConferenceRecordingWithHttpInfo(accountId, conferenceId, recordingId);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.IsType<Stream>(response.Data);
        }

        /// <summary>
        /// Test GetConference
        /// </summary>
        [Fact]
        public void GetConferenceTest()
        {
            ApiResponse<Conference> response = instance.GetConferenceWithHttpInfo(accountId, conferenceId);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.IsType<Conference>(response.Data);
            Assert.Equal(50, response.Data.Id.Length);
            Assert.IsType<string>(response.Data.Name);
            Assert.IsType<DateTime>(response.Data.CreatedTime);
            Assert.IsType<DateTime>(response.Data.CompletedTime);
            Assert.IsType<string>(response.Data.ConferenceEventUrl);
            Assert.IsType<CallbackMethodEnum>(response.Data.ConferenceEventMethod);
            Assert.IsType<string>(response.Data.Tag);
            Assert.IsType<List<ConferenceMember>>(response.Data.ActiveMembers);
        }

        /// <summary>
        /// Test GetConferenceMember
        /// </summary>
        [Fact]
        public void GetConferenceMemberTest()
        {
            ApiResponse<ConferenceMember> response = instance.GetConferenceMemberWithHttpInfo(accountId, conferenceId, callId);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.IsType<ConferenceMember>(response.Data);
            Assert.Equal(47, response.Data.CallId.Length);
            Assert.Equal(50, response.Data.ConferenceId.Length);
            Assert.IsType<string>(response.Data.MemberUrl);
            Assert.IsType<bool>(response.Data.Mute);
            Assert.IsType<bool>(response.Data.Hold);
            Assert.IsType<List<string>>(response.Data.CallIdsToCoach);
        }

        /// <summary>
        /// Test GetConferenceRecording
        /// </summary>
        [Fact]
        public void GetConferenceRecordingTest()
        {
            ApiResponse<ConferenceRecordingMetadata> response = instance.GetConferenceRecordingWithHttpInfo(accountId, conferenceId, recordingId);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.IsType<ConferenceRecordingMetadata>(response.Data);
            Assert.Equal(7, response.Data.AccountId.Length);
            Assert.Equal(50, response.Data.ConferenceId.Length);
            Assert.IsType<string>(response.Data.Name);
            Assert.Equal(47, response.Data.RecordingId.Length);
            Assert.IsType<string>(response.Data.Duration);
            Assert.IsType<int>(response.Data.Channels);
            Assert.IsType<DateTime>(response.Data.StartTime);
            Assert.IsType<DateTime>(response.Data.EndTime);
            Assert.IsType<FileFormatEnum>(response.Data.FileFormat);
            Assert.IsType<string>(response.Data.Status);
            Assert.IsType<string>(response.Data.MediaUrl);
            Assert.IsType<string>(response.Data.RecordingName);
        }

        /// <summary>
        /// Test ListConferenceRecordings
        /// </summary>
        [Fact]
        public void ListConferenceRecordingsTest()
        {
            ApiResponse<List<ConferenceRecordingMetadata>> response = instance.ListConferenceRecordingsWithHttpInfo(accountId, conferenceId);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.IsType<ConferenceRecordingMetadata>(response.Data[0]);
            Assert.Equal(7, response.Data[0].AccountId.Length);
            Assert.Equal(50, response.Data[0].ConferenceId.Length);
            Assert.IsType<string>(response.Data[0].Name);
            Assert.Equal(47, response.Data[0].RecordingId.Length);
            Assert.IsType<string>(response.Data[0].Duration);
            Assert.IsType<int>(response.Data[0].Channels);
            Assert.IsType<DateTime>(response.Data[0].StartTime);
            Assert.IsType<DateTime>(response.Data[0].EndTime);
            Assert.IsType<FileFormatEnum>(response.Data[0].FileFormat);
            Assert.IsType<string>(response.Data[0].Status);
            Assert.IsType<string>(response.Data[0].MediaUrl);
            Assert.IsType<string>(response.Data[0].RecordingName);
        }

        /// <summary>
        /// Test ListConferences
        /// </summary>
        [Fact]
        public void ListConferencesTest()
        {
            ApiResponse<List<Conference>> response = instance.ListConferencesWithHttpInfo(accountId, conferenceId);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.IsType<Conference>(response.Data[0]);
            Assert.Equal(50, response.Data[0].Id.Length);
            Assert.IsType<string>(response.Data[0].Name);
            Assert.IsType<DateTime>(response.Data[0].CreatedTime);
            Assert.IsType<DateTime>(response.Data[0].CompletedTime);
            Assert.IsType<string>(response.Data[0].ConferenceEventUrl);
            Assert.IsType<CallbackMethodEnum>(response.Data[0].ConferenceEventMethod);
            Assert.IsType<string>(response.Data[0].Tag);
        }

        /// <summary>
        /// Test UpdateConference
        /// </summary>
        [Fact]
        public void UpdateConferenceTest()
        {
            UpdateConference conference = new(
                status: ConferenceStateEnum.Active,
                redirectUrl: callbackUrl,
                redirectMethod: RedirectMethodEnum.POST,
                username: "username",
                password: "password",
                redirectFallbackUrl: callbackUrl,
                redirectFallbackMethod: RedirectMethodEnum.POST,
                fallbackUsername: "username",
                fallbackPassword: "password"
            );

            ApiResponse<object> response = instance.UpdateConferenceWithHttpInfo(accountId, conferenceId, conference);

            Assert.Equal(HttpStatusCode.NoContent, response.StatusCode);
        }

        /// <summary>
        /// Test UpdateConferenceBxml
        /// </summary>
        [Fact]
        public void UpdateConferenceBxmlTest()
        {
            string updateConferenceBxml = "<Response><Hangup/></Response>";

            ApiResponse<object> response = instance.UpdateConferenceBxmlWithHttpInfo(accountId, conferenceId, updateConferenceBxml);

            Assert.Equal(HttpStatusCode.NoContent, response.StatusCode);
        }

        /// <summary>
        /// Test UpdateConferenceMember
        /// </summary>
        [Fact]
        public void UpdateConferenceMemberTest()
        {
            UpdateConferenceMember conferenceMember = new(
                mute: true,
                hold: true,
                callIdsToCoach: new List<string>()
            );

            ApiResponse<object> response = instance.UpdateConferenceMemberWithHttpInfo(accountId, conferenceId, callId, conferenceMember);

            Assert.Equal(HttpStatusCode.NoContent, response.StatusCode);
        }
    }
}
