/*
 * Bandwidth
 *
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Net;
using Xunit;

using Bandwidth.Standard.Client;
using Bandwidth.Standard.Api;
using Bandwidth.Standard.Model;

namespace Bandwidth.Standard.Test.Unit.Api
{
    /// <summary>
    ///  PhoneNumberLookupApi Unit Tests
    /// </summary>
    public class PhoneNumberLookupApiTests : IDisposable
    {
        private readonly PhoneNumberLookupApi instance;

        private readonly string accountId = Environment.GetEnvironmentVariable("BW_ACCOUNT_ID");

        public PhoneNumberLookupApiTests()
        {
            Configuration configuration = new()
            {
                BasePath = "http://127.0.0.1:4010",
                IgnoreOperationServers = true,
                OAuthClientId = Environment.GetEnvironmentVariable("BW_CLIENT_ID"),
                OAuthClientSecret = Environment.GetEnvironmentVariable("BW_CLIENT_SECRET")
            };
            instance = new PhoneNumberLookupApi(configuration);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhoneNumberLookupApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            Assert.IsType<PhoneNumberLookupApi>(instance);
        }

        /// <summary>
        /// Test CreateAsyncBulkLookup
        /// </summary>
        [Fact]
        public void CreateAsyncBulkLookupTest()
        {
            AsyncLookupRequest asyncLookupRequest = new(
                phoneNumbers: new List<string> { "+1234567890", "+1987654321" }
            );

            ApiResponse<CreateAsyncBulkLookupResponse> response = instance.CreateAsyncBulkLookupWithHttpInfo(accountId, asyncLookupRequest);

            Assert.Equal(HttpStatusCode.Accepted, response.StatusCode);
            Assert.IsType<CreateAsyncBulkLookupResponse>(response.Data);
            Assert.IsType<List<LinkSchema>>(response.Data.Links);
            Assert.IsType<LinkSchema>(response.Data.Links[0]);
            Assert.IsType<string>(response.Data.Links[0].Rel);
            Assert.IsType<string>(response.Data.Links[0].Href);
            Assert.IsType<string>(response.Data.Links[0].Method);
            Assert.IsType<CreateAsyncBulkLookupResponseData>(response.Data.Data);
            Assert.IsType<Guid>(response.Data.Data.RequestId);
            Assert.IsType<InProgressLookupStatusEnum>(response.Data.Data.Status);
            Assert.Equal(InProgressLookupStatusEnum.INPROGRESS, response.Data.Data.Status);
            Assert.IsType<List<LookupErrorSchema>>(response.Data.Errors);
        }

        /// <summary>
        /// Test CreateSyncLookup
        /// </summary>
        [Fact]
        public void CreateSyncLookupTest()
        {
            SyncLookupRequest syncLookupRequest = new(
                phoneNumbers: new List<string> { "+1234567890", "+1987654321" },
                rcsAgent: "TestAgent"
            );

            ApiResponse<CreateSyncLookupResponse> response = instance.CreateSyncLookupWithHttpInfo(accountId, syncLookupRequest);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.IsType<CreateSyncLookupResponse>(response.Data);
            Assert.IsType<List<LinkSchema>>(response.Data.Links);
            Assert.IsType<CreateSyncLookupResponseData>(response.Data.Data);
            Assert.IsType<Guid>(response.Data.Data.RequestId);
            Assert.IsType<CompletedLookupStatusEnum>(response.Data.Data.Status);
            Assert.Equal(CompletedLookupStatusEnum.COMPLETE, response.Data.Data.Status);
            Assert.IsType<List<LookupResult>>(response.Data.Data.Results);
            Assert.IsType<LookupResult>(response.Data.Data.Results[0]);
            Assert.IsType<string>(response.Data.Data.Results[0].PhoneNumber);
            Assert.IsType<LineTypeEnum>(response.Data.Data.Results[0].LineType);
            Assert.IsType<string>(response.Data.Data.Results[0].MessagingProvider);
            Assert.IsType<string>(response.Data.Data.Results[0].VoiceProvider);
            Assert.IsType<string>(response.Data.Data.Results[0].CountryCodeA3);
            Assert.IsType<LatestMessageDeliveryStatusEnum>(response.Data.Data.Results[0].LatestMessageDeliveryStatus);
            Assert.Equal(LatestMessageDeliveryStatusEnum.ACTIVE, response.Data.Data.Results[0].LatestMessageDeliveryStatus);
            Assert.IsType<DateTime>(response.Data.Data.Results[0].InitialMessageDeliveryStatusDate);
            Assert.IsType<DateTime>(response.Data.Data.Results[0].LatestMessageDeliveryStatusDate);
            Assert.IsType<List<LookupErrorSchema>>(response.Data.Errors);
        }

        /// <summary>
        /// Test GetAsyncBulkLookup
        /// </summary>
        [Fact]
        public void GetAsyncBulkLookupTest()
        {
            Guid requestId = Guid.Parse("123e4567-e89b-12d3-a456-426614174000");

            ApiResponse<GetAsyncBulkLookupResponse> response = instance.GetAsyncBulkLookupWithHttpInfo(accountId, requestId);

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.IsType<GetAsyncBulkLookupResponse>(response.Data);
            Assert.IsType<List<LinkSchema>>(response.Data.Links);
            Assert.IsType<GetAsyncBulkLookupResponseData>(response.Data.Data);
            Assert.IsType<Guid>(response.Data.Data.RequestId);
            Assert.IsType<InProgressLookupStatusEnum>(response.Data.Data.Status);
            Assert.Equal(InProgressLookupStatusEnum.COMPLETE, response.Data.Data.Status);
            Assert.IsType<List<LookupResult>>(response.Data.Data.Results);
            Assert.IsType<LookupResult>(response.Data.Data.Results[0]);
            Assert.IsType<string>(response.Data.Data.Results[0].PhoneNumber);
            Assert.IsType<LineTypeEnum>(response.Data.Data.Results[0].LineType);
            Assert.IsType<string>(response.Data.Data.Results[0].MessagingProvider);
            Assert.IsType<string>(response.Data.Data.Results[0].VoiceProvider);
            Assert.IsType<string>(response.Data.Data.Results[0].CountryCodeA3);
            Assert.IsType<LatestMessageDeliveryStatusEnum>(response.Data.Data.Results[0].LatestMessageDeliveryStatus);
            Assert.Equal(LatestMessageDeliveryStatusEnum.ACTIVE, response.Data.Data.Results[0].LatestMessageDeliveryStatus);
            Assert.IsType<DateTime>(response.Data.Data.Results[0].InitialMessageDeliveryStatusDate);
            Assert.IsType<DateTime>(response.Data.Data.Results[0].LatestMessageDeliveryStatusDate);
            Assert.IsType<List<LookupErrorSchema>>(response.Data.Errors);
        }
    }
}
