name: Deploy
on:
  release:
    types:
      - published
jobs:
  build:
    name: Build
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.x'
      - run: dotnet build
