name: Deploy
on:
  release:
    types:
      - published
jobs:
  build:
    name: Build
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}
          BW_PROJECT_NAME: Bandwidth.Standard
        run: dotnet pack --configuration Release $BW_PROJECT_NAME
        run: dotnet nuget push $BW_PROJECT_NAME/bin/Release/*.nupkg
